### ISSUE TITLE
Theming of plugin-backlight is missing in all themes

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-themes#34]
##### Expected Behavior

The slider of plugin-backlight should be similar to the volume slider  in each theme.
##### Current Behavior

It's always the same: black on white.
##### Possible Solution

Tried adapting volume settings css, but working are only the 2 buttons:
```

/*
Backlight Plugin
*/
#BacklightPlugin QToolButton{
   margin: 2px;
   padding: 2px;
   background:#162635;
}
#BacklightPlugin QToolButton:hover {
   background: #1899da;
   border-radius:2px;
}
BacklightPluginPopup {
   background-color:#041b27;
   margin: 2px;
   padding: 2px;
   border-radius:2px;
}
BacklightPopup  > QPushButton {
   color: #142e35;
   background: #1899da ;
   padding: 2px 10px;
   margin: 5px;
   border:1px solid black;
   qproperty-iconSize: 20px;
   border-radius:2px;
}
BacklightPopup  > QPushButton:hover {
   background:#1aa9f0;
}
BacklightPopup  > QSlider::groove:vertical {
   background: hsv(0, 0, 9);
   width: 8px;
   border-radius: 3px;
}
BacklightPopup  > QSlider::handle:vertical {
   height: 8px;
   background: #1899da;
   border-radius: 2px;
   margin: 0 -4px; /* expand outside the groove */
}
BacklightPopup  > QSlider::add-page:vertical {
   background-color:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #adadad, stop:1 #d1dedd);
   border: 1px solid palette(text);
   border-radius: 3px;
}
BacklightPopup  > QSlider::sub-page:vertical {
   background: rgba(0, 0, 0, 80%);
   border-radius: 3px;
}

**Comment by tsujan** [comment]
The source should be consulted for finding the widgets. The plugin ID is `Backlight` (shown by `#Backlight` in QSS file). It's popup is a dialog called `SliderDialog` and that dialog has a `QSlider`.

The following example is an extremely ugly style that only shows how to use the above-mentioned widgets:

```css
#Backlight > SliderDialog {
    background: red;
}

#Backlight > SliderDialog > QSlider {
	min-width: 16px;
	max-width: 16px;
}

#Backlight > SliderDialog > QSlider::groove:vertical {
	background-color: yellow;
	width: 2px; /* thin groove */
}

#Backlight > SliderDialog > QSlider::handle:vertical {
	background-color: green;
	border: 1px solid green;
	height: 14px; /* 16 - 1 - 1 */
	border-radius: 8px; /* 16/2 */
	margin: 0px -7px; /* 7 = 16/2 - 1 */
}
```
Qt's slider stylesheet is terrible but it can be handled by having a headache. In the above example, the (negative) handle right and left margins (7+7) + the right and left border sizes (1+1) = 16. The handle height + top border + bottom border is also 16. Finally, the border radius is 16/2, which results in a circle.
